name: Run All Tests
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
              env: ${{secrets.MONGODB_URL_TEST}}
            - name: Install dependencies
              run: npm ci
            - run: npm build
            - run: npm test
